/*
 * This file is generated by jOOQ.
 */
package br.com.pedrobelmino.springbootjooq.database.information_schema.tables.records;


import br.com.pedrobelmino.springbootjooq.database.information_schema.tables.EnumValues;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnumValuesRecord extends TableRecordImpl<EnumValuesRecord> implements Record7<String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>INFORMATION_SCHEMA.ENUM_VALUES.OBJECT_CATALOG</code>.
     */
    public void setObjectCatalog(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.ENUM_VALUES.OBJECT_CATALOG</code>.
     */
    public String getObjectCatalog() {
        return (String) get(0);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.ENUM_VALUES.OBJECT_SCHEMA</code>.
     */
    public void setObjectSchema(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.ENUM_VALUES.OBJECT_SCHEMA</code>.
     */
    public String getObjectSchema() {
        return (String) get(1);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.ENUM_VALUES.OBJECT_NAME</code>.
     */
    public void setObjectName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.ENUM_VALUES.OBJECT_NAME</code>.
     */
    public String getObjectName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.ENUM_VALUES.OBJECT_TYPE</code>.
     */
    public void setObjectType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.ENUM_VALUES.OBJECT_TYPE</code>.
     */
    public String getObjectType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.ENUM_VALUES.ENUM_IDENTIFIER</code>.
     */
    public void setEnumIdentifier(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.ENUM_VALUES.ENUM_IDENTIFIER</code>.
     */
    public String getEnumIdentifier() {
        return (String) get(4);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.ENUM_VALUES.VALUE_NAME</code>.
     */
    public void setValueName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.ENUM_VALUES.VALUE_NAME</code>.
     */
    public String getValueName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>INFORMATION_SCHEMA.ENUM_VALUES.VALUE_ORDINAL</code>.
     */
    public void setValueOrdinal(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>INFORMATION_SCHEMA.ENUM_VALUES.VALUE_ORDINAL</code>.
     */
    public String getValueOrdinal() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return EnumValues.ENUM_VALUES.OBJECT_CATALOG;
    }

    @Override
    public Field<String> field2() {
        return EnumValues.ENUM_VALUES.OBJECT_SCHEMA;
    }

    @Override
    public Field<String> field3() {
        return EnumValues.ENUM_VALUES.OBJECT_NAME;
    }

    @Override
    public Field<String> field4() {
        return EnumValues.ENUM_VALUES.OBJECT_TYPE;
    }

    @Override
    public Field<String> field5() {
        return EnumValues.ENUM_VALUES.ENUM_IDENTIFIER;
    }

    @Override
    public Field<String> field6() {
        return EnumValues.ENUM_VALUES.VALUE_NAME;
    }

    @Override
    public Field<String> field7() {
        return EnumValues.ENUM_VALUES.VALUE_ORDINAL;
    }

    @Override
    public String component1() {
        return getObjectCatalog();
    }

    @Override
    public String component2() {
        return getObjectSchema();
    }

    @Override
    public String component3() {
        return getObjectName();
    }

    @Override
    public String component4() {
        return getObjectType();
    }

    @Override
    public String component5() {
        return getEnumIdentifier();
    }

    @Override
    public String component6() {
        return getValueName();
    }

    @Override
    public String component7() {
        return getValueOrdinal();
    }

    @Override
    public String value1() {
        return getObjectCatalog();
    }

    @Override
    public String value2() {
        return getObjectSchema();
    }

    @Override
    public String value3() {
        return getObjectName();
    }

    @Override
    public String value4() {
        return getObjectType();
    }

    @Override
    public String value5() {
        return getEnumIdentifier();
    }

    @Override
    public String value6() {
        return getValueName();
    }

    @Override
    public String value7() {
        return getValueOrdinal();
    }

    @Override
    public EnumValuesRecord value1(String value) {
        setObjectCatalog(value);
        return this;
    }

    @Override
    public EnumValuesRecord value2(String value) {
        setObjectSchema(value);
        return this;
    }

    @Override
    public EnumValuesRecord value3(String value) {
        setObjectName(value);
        return this;
    }

    @Override
    public EnumValuesRecord value4(String value) {
        setObjectType(value);
        return this;
    }

    @Override
    public EnumValuesRecord value5(String value) {
        setEnumIdentifier(value);
        return this;
    }

    @Override
    public EnumValuesRecord value6(String value) {
        setValueName(value);
        return this;
    }

    @Override
    public EnumValuesRecord value7(String value) {
        setValueOrdinal(value);
        return this;
    }

    @Override
    public EnumValuesRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnumValuesRecord
     */
    public EnumValuesRecord() {
        super(EnumValues.ENUM_VALUES);
    }

    /**
     * Create a detached, initialised EnumValuesRecord
     */
    public EnumValuesRecord(String objectCatalog, String objectSchema, String objectName, String objectType, String enumIdentifier, String valueName, String valueOrdinal) {
        super(EnumValues.ENUM_VALUES);

        setObjectCatalog(objectCatalog);
        setObjectSchema(objectSchema);
        setObjectName(objectName);
        setObjectType(objectType);
        setEnumIdentifier(enumIdentifier);
        setValueName(valueName);
        setValueOrdinal(valueOrdinal);
    }
}
