/*
 * This file is generated by jOOQ.
 */
package br.com.pedrobelmino.springbootjooq.database.public_;


import br.com.pedrobelmino.springbootjooq.database.public_.tables.Author;
import br.com.pedrobelmino.springbootjooq.database.public_.tables.AuthorBook;
import br.com.pedrobelmino.springbootjooq.database.public_.tables.Book;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.AUTHOR</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>PUBLIC.AUTHOR_BOOK</code>.
     */
    public static final AuthorBook AUTHOR_BOOK = AuthorBook.AUTHOR_BOOK;

    /**
     * The table <code>PUBLIC.BOOK</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
